#!/bin/bash
cat <<'EOF'
  ____  _                                                                           
 / ___|| |_ ___  _ __                                                               
 \___ \| __/ _ \| '_ \                                                              
  ___) | || (_) | |_) |                                                             
 |____/ \__\___/| .__/ _    __  __    _      ____                                   
  / _ \| |   | ||_|   / \  |  \/  |  / \    |  _ \  __ _  ___ _ __ ___   ___  _ __  
 | | | | |   | |     / _ \ | |\/| | / _ \   | | | |/ _` |/ _ \ '_ ` _ \ / _ \| '_ \ 
 | |_| | |___| |___ / ___ \| |  | |/ ___ \  | |_| | (_| |  __/ | | | | | (_) | | | |
  \___/|_____|_____/_/   \_\_|  |_/_/   \_\ |____/ \__,_|\___|_| |_| |_|\___/|_| |_|
                                                                               v1.0               
EOF
OLLAMA_DIR=`dirname $0`
MAIN_DIR=`realpath "$OLLAMA_DIR/.."`

CONTAINER_NAME=${USER}-ollama
COMMAND=`${OLLAMA_DIR}/container_command.sh`

echo "Stopping the OLLAMA daemon."
${COMMAND} stop ${CONTAINER_NAME}
${COMMAND} rm -f ${CONTAINER_NAME}
echo "Done."